travis:
  secure:
    BINSTAR_TOKEN: uB3/VUFMmZq3PRyBunIoNolSxM0VFPwFTawSg+nRcgEHkP/RdWIFWOlGeGFepZk6EQuPn19Ww7dYW8B1icgiVPVLx9POiHS5JohbjWxCyWB6jm1fYre51M0m/5W1hmCWSkhDCXc9FV1iTfPzJkseF2CbU+HvGcqMjwW2pwPLx3hE0vvwur/Mz6VaWgNxqmrjw65+CuxuzzDyt8hwE0fl+gJwYHnuZBssAV2SDDxvWdX/H038XqEyLr8qtsoMNB3shzn0ixbtKI1cisELcvDA5iQd2a5kX6MgSTn+NbvY0/YZjjt6owv4naq++CgfL7WRWJ5sbnrMSRS6UhE5O6cBDuDezHVHnP5ar/bYJPQa4rZLohXYy7ACc9p4S/7M8MpZH6XouvvOxC+gN4ehnZmjC9LGGagIvaAJ1b6sTLG0PlOPF93ApJYyteGGXFGiS3NmchAWQkZshm97+VGINfpZiXnSe4NvZ/la1iqYVL8yuf0v2WQmST2EgndHF65lf+1yOxn/u7gHc2ECS+n8i4acpuYE+kuIfxLkS1mMUhQngIwcny9gnOzDMvmz9rkeaCXuH/4b/xFbX8yMjt+qOeF4b49S6hTA43XRjjtdHF5Y58IH44dWufduegqqjyXNoOGaXbIr801D2kYJ20GP81iu+ZbyMwCxJ1tECo8hbuvBlXU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
